### ISSUE TITLE
Please add version for composer.

### ISSUE THREAD

**Issue by pyatnitsev** [gromo/dkron-php-adapter#1]
Hello!

Please, add some release (1.0 maybe) to allow using your library with version(s) not with dev-master version.

**Comment by gromo** [comment]
Hi,

I think it has to be updated to match current version, then I will make release.

**Comment by pyatnitsev** [comment]
What changes you need to make a release?

**Comment by pyatnitsev** [comment]
@gromo I need this, to use stable version (version from dev-master works well for me)

**Comment by gromo** [comment]
@pyatnitsev if current version is ok, I will close this ticket

**Comment by pyatnitsev** [comment]
yes, but what about stable release ?

**Comment by gromo** [comment]
https://github.com/gromo/dkron-php-adapter/releases/tag/v0.10.0 ?

**Comment by pyatnitsev** [comment]
I see. Thanks a lot!
